### ISSUE TITLE
agileiot/agile-ui-armv7l:latest does not exist

### ISSUE THREAD

**Issue by lenada** [Agile-IoT/agile-scripts#2]
https://github.com/Agile-IoT/agile-scripts/blob/master/compose/docker-compose.yml#L47
does not reference an explicit image tag and therefore defaults to `latest`. Unfortunately the `latest` tag does not exist on [docker-hub](https://hub.docker.com/r/agileiot/agile-ui-armv7l/tags/)

which makes `./agile start` fail

I tried to define an existing tag (v0.2.0) locally, so the image could be pulled. It then hung on the wait_for_service "http://localhost:2000" check, which is likely a (different) issue with agile-ui-armv7l?

would it be worth the effort (is it even possible in a sane way?) to also apply continuous integration practices (e.g travis-ci) to this repo to ensure `./agile` commands deliver expected results?

**Comment by cskiraly** [comment]
There are three parts to this:
1, travis CI: our current travis template pushes everything built from the master branch (with a master tag on docker hub) also as "latest" on docker hub. @craig-mulligan improved the template for the UI, but removed this functionality. @craig-mulligan, can you comment on this? Can you re-add the latest? Should/could we adapt your new template with versionist integration all over?

2, while the "latest" tag makes sense, it is always on a shaky ground, since it is about a combination that was not extensively tested. That's why we plan to have tagged releases of the stack, where each component is explicitly versioned.

3,  we are moving away from "agile-scripts" to a combination of "agile-stack" (docker-compose.yml with some extras) and "agile-cli" (a small CLI to manage an agile-stack). This is on-going, but we will deprecate agile-script soon.

**Comment by lenada** [comment]
@cskiraly thank you for the quick response & clarification, I will give `agile-stack`/`agile-cli` a try.
